pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Michael-hanyy/visa_payment.git'
            }
        }

        stage('Docker Build & Run') {
            steps {
                sh '''
                    echo "Stopping old containers..."
                    docker-compose down || true

                    echo "Building and starting Docker containers..."
                    docker-compose up --build -d
                '''
            }
        }

        stage('Run Migrations') {
            steps {
                sh 'docker-compose exec web python manage.py migrate'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker-compose exec web python manage.py test'
            }
        }
    }
}
