pipeline {
    agent any

    
stage('Clone Repo') {
    steps {
        git branch: 'main', url: 'https://github.com/Michael-hanyy/visa_payment.git'
    }
}

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source venv/bin/activate
                    python manage.py test
                '''
            }
        }
    }
}

